// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV2KNXJAJ3NjGAJM2Q782b294gwy8_VXc',
    appId: '1:17179678249:web:b4ef5f8cf92c186a056e38',
    messagingSenderId: '17179678249',
    projectId: 'eos-advanced-b1107',
    authDomain: 'eos-advanced-b1107.firebaseapp.com',
    storageBucket: 'eos-advanced-b1107.firebasestorage.app',
    measurementId: 'G-1JS8E3YW5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD76S5_AX0ycvxa6kHugAZ5rDSa2s64Kt4',
    appId: '1:17179678249:android:ac2cfcbdb7cc9537056e38',
    messagingSenderId: '17179678249',
    projectId: 'eos-advanced-b1107',
    storageBucket: 'eos-advanced-b1107.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiSkmxvJ6Li5KTAInBNqtGalsOzDF9RoY',
    appId: '1:17179678249:ios:86a560ea1e2ede04056e38',
    messagingSenderId: '17179678249',
    projectId: 'eos-advanced-b1107',
    storageBucket: 'eos-advanced-b1107.firebasestorage.app',
    iosBundleId: 'com.example.te',
  );
}
